[package]
name = "tokio_jailer"
version = "0.1.0"
edition = "2021"

[dependencies]
firecracker-rs-sdk = { path = "../../", features = ["_rt-tokio"] }
tokio = { version = "1.43", features = [
    "net",
    "time",
    "io-util",
    "rt",
    "macros",
    "rt-multi-thread",
] }
